spring.datasource.url=jdbc:postgresql://localhost:5432/exerciseworksheet
spring.datasource.username=postgres
spring.datasource.password=123456
spring.application.name=ExerciseWorksheetManager
spring.jpa.generate-ddl = true
spring.jpa.hibernate.ddl-auto=update
spring.profiles.active=test
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
api.security.secret=S3gReDo_MuItO_LonGo_QuE_NiNgUeM_vAi_AdIvInHaR_1234567890abcdef